/** Maps English team names → ISO 3166-1 alpha-2 (or subdivision) codes for circle-flags CDN */
export const FLAG_CODES: Record<string, string> = {
  'Algeria': 'dz',
  'Angola': 'ao',
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Belgium': 'be',
  'Bolivia': 'bo',
  'Bosnia-Herzegovina': 'ba',
  'Bosnia': 'ba',
  'Botswana': 'bw',
  'Brazil': 'br',
  'Bulgaria': 'bg',
  'Cameroon': 'cm',
  'Canada': 'ca',
  'Cape Verde': 'cv',
  'Chile': 'cl',
  'China': 'cn',
  'Colombia': 'co',
  'Costa Rica': 'cr',
  'Croatia': 'hr',
  'Cuba': 'cu',
  'Curacao': 'cw',
  'Czechia': 'cz',
  'Czech Republic': 'cz',
  'Denmark': 'dk',
  'DR Congo': 'cd',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'El Salvador': 'sv',
  'England': 'gb-eng',
  'France': 'fr',
  'Germany': 'de',
  'Ghana': 'gh',
  'Greece': 'gr',
  'Guatemala': 'gt',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Hungary': 'hu',
  'India': 'in',
  'Indonesia': 'id',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Ireland': 'ie',
  'Italy': 'it',
  'Ivory Coast': 'ci',
  'Jamaica': 'jm',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Kazakhstan': 'kz',
  'Kenya': 'ke',
  'Lebanon': 'lb',
  'Mexico': 'mx',
  'Morocco': 'ma',
  'Netherlands': 'nl',
  'New Zealand': 'nz',
  'Nicaragua': 'ni',
  'Nigeria': 'ng',
  'Norway': 'no',
  'Panama': 'pa',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Romania': 'ro',
  'Saudi Arabia': 'sa',
  'Scotland': 'gb-sct',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'South Africa': 'za',
  'South Korea': 'kr',
  'South Sudan': 'ss',
  'Spain': 'es',
  'Sudan': 'sd',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Thailand': 'th',
  'Tunisia': 'tn',
  'Turkey': 'tr',
  'Turkmenistan': 'tm',
  'Ukraine': 'ua',
  'United States': 'us',
  'Uruguay': 'uy',
  'Uzbekistan': 'uz',
  'Venezuela': 've',
  'Wales': 'gb-wls',
  'Yemen': 'ye',
}

const CDN = 'https://hatscripts.github.io/circle-flags/flags'

export function flagUrl(team: string): string | null {
  const code = FLAG_CODES[team]
  return code ? `${CDN}/${code}.svg` : null
}
