export const teamNamesPT: Record<string, string> = {
  'Mexico': 'México',
  'South Africa': 'África do Sul',
  'South Korea': 'Coreia do Sul',
  'Czechia': 'Rep. Tcheca',
  'Czech Republic': 'Rep. Tcheca',
  'Canada': 'Canadá',
  'Bosnia-Herzegovina': 'Bósnia-Herz.',
  'United States': 'Estados Unidos',
  'Paraguay': 'Paraguai',
  'Qatar': 'Catar',
  'Switzerland': 'Suíça',
  'Brazil': 'Brasil',
  'Morocco': 'Marrocos',
  'Argentina': 'Argentina',
  'Australia': 'Austrália',
  'France': 'França',
  'Germany': 'Alemanha',
  'Japan': 'Japão',
  'Croatia': 'Croácia',
  'Spain': 'Espanha',
  'Netherlands': 'Holanda',
  'Portugal': 'Portugal',
  'England': 'Inglaterra',
  'Italy': 'Itália',
  'Belgium': 'Bélgica',
  'Uruguay': 'Uruguai',
  'Colombia': 'Colômbia',
  'Ecuador': 'Equador',
  'Serbia': 'Sérvia',
  'Denmark': 'Dinamarca',
  'Poland': 'Polônia',
  'Senegal': 'Senegal',
  'Nigeria': 'Nigéria',
  'Ghana': 'Gana',
  'Egypt': 'Egito',
  'Tunisia': 'Tunísia',
  'Cameroon': 'Camarões',
  'Saudi Arabia': 'Arábia Saudita',
  'Iran': 'Irã',
  'New Zealand': 'Nova Zelândia',
  'Costa Rica': 'Costa Rica',
  'Chile': 'Chile',
  'Peru': 'Peru',
  'Venezuela': 'Venezuela',
  'Honduras': 'Honduras',
  'Jamaica': 'Jamaica',
  'Cuba': 'Cuba',
  'Scotland': 'Escócia',
  'Wales': 'País de Gales',
  'Ireland': 'Irlanda',
  'Norway': 'Noruega',
  'Sweden': 'Suécia',
  'Austria': 'Áustria',
  'Hungary': 'Hungria',
  'Slovakia': 'Eslováquia',
  'Slovenia': 'Eslovênia',
  'Romania': 'Romênia',
  'Bulgaria': 'Bulgária',
  'Greece': 'Grécia',
  'Turkey': 'Turquia',
  'Ukraine': 'Ucrânia',
  'Algeria': 'Argélia',
  'Sudan': 'Sudão',
  'South Sudan': 'Sudão do Sul',
  'Kenya': 'Quênia',
  'Angola': 'Angola',
  "Ivory Coast": 'Costa do Marfim',
  'Botswana': 'Botsuana',
  'Lebanon': 'Líbano',
  'Iraq': 'Iraque',
  'Yemen': 'Iêmen',
  'Kazakhstan': 'Cazaquistão',
  'Turkmenistan': 'Turcomenistão',
  'India': 'Índia',
  'China': 'China',
  'Thailand': 'Tailândia',
  'Indonesia': 'Indonésia',
  'Panama': 'Panamá',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Nicaragua': 'Nicarágua',
  'Bolivia': 'Bolívia',
  'TBD': 'A definir',
  'Cape Verde': 'Cabo Verde',
  'Cabo Verde': 'Cabo Verde',
  'Curacao': 'Curaçao',
  'Curaçao': 'Curaçao',
  'DR Congo': 'Rep. Dem. do Congo',
  'Congo DR': 'Rep. Dem. do Congo',
  'Democratic Republic of Congo': 'Rep. Dem. do Congo',
  'Democratic Republic of the Congo': 'Rep. Dem. do Congo',
  'Haiti': 'Haiti',
  'Jordan': 'Jordânia',
}

export function translateTeam(name: string): string {
  return teamNamesPT[name] ?? name
}
